server:
  port: 8085

spring:
  application:
    name: personal-service
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME_PERSONAL:personal}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        "[format_sql]": true
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

app:
  jwt:
    secret: ${JWT_SECRET:CHANGE_ME_IN_PRODUCTION_MIN_256_BITS_FOR_HS256_SECURITY}
    expiration: 86400000
  security:
    bcrypt-strength: 12

logging:
  level:
    root: INFO
    "[main.java.com.suances.personnel]": DEBUG
    "[org.springframework.security]": INFO
