services:
  media-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: suances-media-service
    ports:
      - "8080:8080"
    env_file:
      - ../../.env
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    networks:
      - suances-network

networks:
  suances-network:
    external: true
    # We reference the network created by docker-compose-infra.yml
    name: suances_suances-network
